// <auto-generated />
using System;
using Game.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Game.Infrastructure.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Game.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("WinningTeam")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("CourtId", "ScheduledAt")
                        .IsUnique()
                        .HasDatabaseName("ux_games_court_scheduled_at")
                        .HasFilter("\"Status\" <> 'Cancelled'");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Game.Domain.Entities.GameParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "UserId")
                        .IsUnique();

                    b.ToTable("game_participants", (string)null);
                });

            modelBuilder.Entity("Game.Domain.Entities.GameSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TeamOneGames")
                        .HasColumnType("integer");

                    b.Property<int>("TeamTwoGames")
                        .HasColumnType("integer");

                    b.Property<int?>("TieBreakTeamOne")
                        .HasColumnType("integer");

                    b.Property<int?>("TieBreakTeamTwo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "SetNumber")
                        .IsUnique();

                    b.ToTable("game_sets", (string)null);
                });

            modelBuilder.Entity("Game.Domain.Entities.PlayerRanking", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("GamesWon")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RankingPoints")
                        .HasColumnType("integer");

                    b.Property<int>("SetsLost")
                        .HasColumnType("integer");

                    b.Property<int>("SetsWon")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("player_rankings", (string)null);
                });

            modelBuilder.Entity("Game.Domain.Entities.GameParticipant", b =>
                {
                    b.HasOne("Game.Domain.Entities.Game", null)
                        .WithMany("Participants")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Game.Domain.Entities.GameSet", b =>
                {
                    b.HasOne("Game.Domain.Entities.Game", null)
                        .WithMany("Sets")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Game.Domain.Entities.Game", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
